### ISSUE TITLE
Deprecated Methods, Constructor and missing jar file 

### ISSUE THREAD

**Issue by Abime001** [v-bonilla/lexical-syntactic-semantic-analyser#1]
In the file Scanner.java, line 75 to 78, the method finalize() is deprecated since Version 9 of Java, the same way, the constructor named Integer is deprecated, the lines where this constructors appears are from 296 to 305 (in the same file: Scanner.java). 
i think the JAR file where you refers in the README, "Procesador.java" is missing.

**Comment by v-bonilla** [comment]
Hi @Abime001, thank you for raising the issue.
First of all, I'd like to mention that there isn't intention to maintain or update this project. It was simply a project to learn.

Regarding the deprecated methods, the project was developed with Java 8 and it is supposed to be executed with that Java version.

On the other hand, it is supposed that the user needs to export the JAR file by him/herself to avoid potential security issues (see [this deep instinct blog post](https://www.deepinstinct.com/blog/a-jar-of-malware) as ilustration). In case it helps, here are two stackoverflow questions talking about exporting as JAR: [first](https://stackoverflow.com/questions/4597866/java-creating-jar-file), [second](https://stackoverflow.com/questions/423938/java-export-to-an-jar-file-in-eclipse).
